# Generated by Django 4.0.2 on 2022-02-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialchange',
            name='amount_gr',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
