# Generated by Django 4.0.2 on 2022-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financialchange_amount_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialchange',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_gr',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
