# Generated by Django 4.0.2 on 2022-04-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transfer_saldo_alter_financialchange_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='saldo',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='operation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='posting_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='outer_account',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender_receiver',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
