# Generated by Django 4.0.2 on 2022-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_saldo_transfer_balance_remove_transfer_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('I', 'Inserted'), ('P', 'Postponed')], max_length=1, null=True),
        ),
    ]
